version: "3.8"

services:
  config-server:
    container_name: config-server
    build: ./config-server
    ports:
      - "8888:8888"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/

  discovery-service:
    container_name: discovery-service
    build: ./discovery
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    depends_on:
      - config-server

  gateway-service:
    container_name: gateway-service
    image: gateway-service
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8222:8222"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - config-server
      - hackathon-service
      - discovery-service

  hackathon-service:
    container_name: hackathon-service
    image: hackathon-service
    build:
      context: ./hackathon
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    hostname: hackathon
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql:3306/hackathon?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=slimfady.hanafi7@gmail.com
      - SPRING_MAIL_PASSWORD=avdvbwwhmoqxlrtk
    depends_on:
      - config-server
      - discovery-service
      - docker-mysql
      - forum-service

  forum-service:
    container_name: forum-service
    image: forum-service
    build:
      context: ./forum
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    hostname: forum
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql:3306/forum?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=slimfady.hanafi7@gmail.com
      - SPRING_MAIL_PASSWORD=avdvbwwhmoqxlrtk
    depends_on:
      - config-server
      - discovery-service
      - docker-mysql

  docker-mysql:
    container_name: docker-mysql
    image: mysql:8.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=forum
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  mysql-data:
