spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: formation-service
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka