apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices
data:
  # MySQL Configuration
  MYSQL_DATABASE: "UserPI"
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  # Eureka configuration
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"


  # Spring Configuration
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SPRING_CLOUD_CONFIG_URI: "http://config-server-service:8888"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://discovery-service:8761/eureka/"

  # Database URL
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/UserPI?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
  SPRING_DATASOURCE_USERNAME: "root"

  # Email Configuration
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  APP_MAIL_FROM: "saifromdhani707@gmail.com"
  APP_FRONTEND_URL: "http://localhost:4200"
  APP_CORS_ALLOWED_ORIGINS: "http://localhost:4200"



