apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices
type: Opaque
data:
  # JWT_SECRET: Y6ThdM9XcJb35ZBYzLH7HhT7dwFDAJ0dUVZn7pa9JIE= (this is already base64 encoded)
  JWT_SECRET: Y6ThdM9XcJb35ZBYzLH7HhT7dwFDAJ0dUVZn7pa9JIE=
  # Empty password for MySQL root (base64 encoded empty string)
  MYSQL_ROOT_PASSWORD: ""
  # Gmail app password: dfswhascenogfexh (base64 encoded)
  MAIL_PASSWORD: ZGZzd2hhc2Nlbm9nZmV4aA==
  # Gmail username: saifromdhani707@gmail.com (base64 encoded)
  MAIL_USERNAME: c2FpZnJvbWRoYW5pNzA3QGdtYWlsLmNvbQ==
  # Mail From (saifromdhani707@gmail.com)
  APP_MAIL_FROM: c2FpZnJvbWRoYW5pNzA3QGdtYWlsLmNvbQ==