spring.application.name=user-service
spring.config.import=optional:configserver:http://localhost:8888,optional:file:.env[.properties]


app.cors.allowed-origins=http://localhost:4200
app.frontend.base-url=http://localhost:4200
app.frontend.verify-email-path=/verify-email
app.frontend.reset-password-path=/reset-password

spring.main.allow-bean-definition-overriding=true

# SWAGGER CONFIG
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=com.saifeddine.user.controller
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.info.title=User Management API
springdoc.info.description=API documentation for User Management System
springdoc.info.version=1.0.0
springdoc.server-url=http://localhost:8090/api
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.url=/v3/api-docs

# Configuration pour le clustering
app.clustering.modelPath=classpath:kmeans_model.model
app.clustering.clusterCount=3


# Configuration des logs
logging.level.com.saifeddine.user=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saifromdhani707@gmail.com
spring.mail.password=dfswhascenogfexh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
app.mail.from=saifromdhani707@gmail.com
app.frontend.url=http://localhost:4200