server:
  port: 8090

spring:
  application:
    name: forum-service
  datasource:
    url: jdbc:mysql://localhost:3306/forum?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: slimfady.hanafi7@gmail.com
    password: avdvbwwhmoqxlrtk
    properties:
      mail:
        test-connection: true
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
