server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # découvrir automatiquement les services enregistrés dans Eureka.
      routes:
        - id: forum-service
          uri: lb:http://FORUM-SERVICE  # redirige vers FORUM-SERVICE a partir du load balencer (instance)
          predicates:
            - Path=/api/v1/forums/**  # vers http://localhost:8222/api/v1/forums/**
        - id: hackathon-service
          uri: lb:http://HACKATHON-SERVICE
          predicates:
            - Path=/api/v1/hackathons/**   # vers http://localhost:8222/api/v1/hackathons/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"  # ng serve
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true  # connexion avec Angular
