server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: forum-service
          uri: lb:http://FORUM-SERVICE
          predicates:
            - Path=/api/v1/forums/**
        - id: hackathon-service
          uri: lb:http://HACKATHON-SERVICE
          predicates:
            - Path=/api/v1/hackathons/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
