server:
  port: 8841

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: Reclamation-service
          uri: http://localhost:8020
          predicates:
            - Path=/Reclamation/**

        - id: Paiement-service
          uri: http://localhost:8021
          predicates:
            - Path=/Paiement/**

  main:
    allow-bean-definition-overriding: true

  # Configuration Eureka
  eureka:
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

# Configuration Swagger (springdoc)
springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
  paths-to-match: /**
  urls:
    - name: Reclamation service
      url: http://localhost:8841/Reclamation/v3/api-docs
    - name: Paiement service
      url: http://localhost:8841/Paiement/v3/api-docs
