server:
  port: 8084

spring:
  application:
    name: internshipoffer-service

  datasource:
    url: jdbc:mysql://localhost:3306/internshipoffer_bismillah_db?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: dorsafriahi6@gmail.com
    password: dwhb llze rgho pqmx
    properties:
      mail:
        test-connection: true
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
