spring:
  application:
    name: Complaint
  datasource:
    url: jdbc:mysql://localhost:3306/web_distribue1?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8020

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

